export const WHATSAPP_NUMBER = process.env.NEXT_PUBLIC_WA_NUMBER ?? '601110528685';
export const ADMIN_PASSWORD = process.env.NEXT_PUBLIC_ADMIN_PASSWORD ?? '';

export const DEFAULT_PRODUCTS = [
  {id:1,name:'Rubber Stamp Super Urgent',category:'Stamps',desc:'Cop getah siap pada hari yang sama. Sesuai untuk keperluan segera.',fullDesc:'Dapatkan cop getah custom anda siap pada hari yang sama. Kami menggunakan bahan photopolymer berkualiti tinggi untuk cetakan yang tajam dan jelas.',icon:'fa-stamp',color:'text-red-500',bg:'bg-red-50',price:'Dari RM 15',featured:true,image:null,options:[{label:'Saiz',choices:['Kecil (20×45mm)','Sedang (30×60mm)','Besar (40×70mm)']},{label:'Warna Ink',choices:['Biru','Merah','Hitam','Hijau']}]},
  {id:2,name:'Rubber Stamp / Cop',category:'Stamps',desc:'Cop getah standard untuk kegunaan pejabat harian.',fullDesc:'Cop getah berkualiti untuk kegunaan harian. Tersedia dalam pelbagai saiz dengan masa pengeluaran yang pantas.',icon:'fa-stamp',color:'text-orange-500',bg:'bg-orange-50',price:'Dari RM 12',featured:true,image:null,options:[{label:'Bentuk',choices:['Petak','Bulat']},{label:'Warna Ink',choices:['Biru','Merah','Hitam']}]},
  {id:3,name:'Common Seal',category:'Stamps',desc:'Cop rasmi syarikat untuk dokumen dan kontrak undang-undang.',fullDesc:'Cop emboss profesional untuk dokumen rasmi syarikat. Memenuhi keperluan undang-undang untuk dokumen yang disahkan di Malaysia.',icon:'fa-certificate',color:'text-amber-600',bg:'bg-amber-50',price:'Request Quote',featured:false,image:null,options:[{label:'Jenis',choices:['Emboss Sahaja','Emboss + Ink Merah','Custom']}]},
  {id:4,name:'Business Card',category:'Cards',desc:'Kad bisnes dicetak secara profesional. Finish matte, gloss atau velvet.',fullDesc:'Tinggalkan kesan pertama yang baik dengan kad bisnes premium. Tersedia dalam saiz standard (90×55mm) dengan pelbagai pilihan finish.',icon:'fa-id-card',color:'text-blue-500',bg:'bg-blue-50',price:'Dari RM 25/100pcs',featured:true,image:null,options:[{label:'Kuantiti',choices:['100 pcs','200 pcs','500 pcs','1000 pcs']},{label:'Finish',choices:['Lamination Matte','Lamination Gloss','Lamination Velvet','Tanpa Lamination']},{label:'Muka',choices:['Satu Muka','Dua Muka']}]},
  {id:5,name:'T-Shirt Printing',category:'Apparel',desc:'Cetakan baju T custom untuk acara, uniform dan merchandise.',fullDesc:'Cetakan baju T berkualiti tinggi menggunakan sublimation dan screen printing.',icon:'fa-tshirt',color:'text-green-500',bg:'bg-green-50',price:'Dari RM 18/pcs',featured:true,image:null,options:[{label:'Jenis Cetakan',choices:['Sublimation','Screen Print','DTF Print','Embroidery']},{label:'Saiz',choices:['XS','S','M','L','XL','XXL','XXXL']},{label:'Lokasi Print',choices:['Depan Sahaja','Belakang Sahaja','Depan & Belakang']}]},
  {id:6,name:'Sticker',category:'Stickers',desc:'Stiker custom dalam apa jua bentuk dan saiz. Pilihan kalis air tersedia.',fullDesc:'Stiker tahan lama dan berwarna-warni untuk penjenamaan, pelabelan dan hiasan.',icon:'fa-tags',color:'text-yellow-600',bg:'bg-yellow-50',price:'Dari RM 10',featured:false,image:null,options:[{label:'Bahan',choices:['Gloss','Matte','Chrome','Transparent']},{label:'Bentuk',choices:['Segi Empat','Bulat','Die-cut']}]},
  {id:7,name:'Car Sticker',category:'Stickers',desc:'Stiker kereta tahan lama dan decal vinyl untuk kenderaan.',fullDesc:'Stiker kereta tahan cuaca menggunakan vinyl outdoor premium.',icon:'fa-car',color:'text-sky-500',bg:'bg-sky-50',price:'Dari RM 25',featured:false,image:null,options:[{label:'Saiz',choices:['Kecil (A5)','Sedang (A4)','Besar (A3)','Custom']},{label:'Jenis',choices:['Cut Sticker','Sticker Print']}]},
  {id:8,name:'Flyers',category:'Print',desc:'Flyers dan risalah menarik untuk promosi dan acara.',fullDesc:'Cetakan flyer warna penuh pada stok kertas berkualiti.',icon:'fa-scroll',color:'text-purple-500',bg:'bg-purple-50',price:'Dari RM 30/100pcs',featured:true,image:null,options:[{label:'Saiz',choices:['A4','A5','A6','DL']},{label:'Kertas',choices:['100gsm','120gsm','150gsm']},{label:'Muka',choices:['Satu Muka','Dua Muka']}]},
  {id:9,name:'Button Badge',category:'Accessories',desc:'Button badge custom untuk acara, kempen dan cenderamata.',fullDesc:'Button badge warna penuh dengan pin keselamatan di belakang.',icon:'fa-circle',color:'text-pink-500',bg:'bg-pink-50',price:'Dari RM 1.50/pcs',featured:false,image:null,options:[{label:'Saiz',choices:['25mm','32mm','44mm','58mm','75mm']}]},
  {id:10,name:'Keychain',category:'Accessories',desc:'Keychain tercetak custom sebagai cenderamata dan merchandise.',fullDesc:'Keychain acrylic atau metal yang diperibadikan dengan design anda.',icon:'fa-key',color:'text-orange-500',bg:'bg-orange-50',price:'Dari RM 3/pcs',featured:false,image:null,options:[{label:'Bahan',choices:['Acrylic','Metal','Getah']},{label:'Bentuk',choices:['Segi Empat','Bulat','Bentuk Custom']}]},
  {id:11,name:'Board',category:'Signage',desc:'Papan tanda, papan nama dan papan paparan untuk kedai dan pejabat.',fullDesc:'Papan tanda profesional menggunakan komposit aluminium atau papan busa PVC.',icon:'fa-sign',color:'text-teal-500',bg:'bg-teal-50',price:'Request Quote',featured:false,image:null,options:[{label:'Bahan',choices:['Komposit Aluminium','PVC Foam','Corflute']},{label:'Saiz',choices:['A2','A1','A0','Custom']}]},
] as const;
